services:
  app:
    build: .
    volumes:
      - ./output:/app/output
    ports:
      - "8080:8080"
    networks:
      - metrics-network

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - metrics-network

volumes:
  grafana-storage:

networks:
  metrics-network:
