name: Set Release Version

on:
    workflow_call:
        inputs:
            version_format:
                type: string
                description: Version format to use for tagging
                required: false
            tag_repo:
                type: boolean
                description: Flag to indicate if GitHub tag needs to be created
                default: false
        outputs:
            version:
                description: Decided version
                value: ${{ jobs.setup-version.outputs.version }}
            version_tag:
                description: Version tag
                value: ${{ jobs.setup-version.outputs.version_tag }}

jobs:
    setup-version:
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.get-version.outputs.version }}
            version_tag: ${{ steps.get-version.outputs.version_tag }}
        steps:
          - uses: actions/checkout@v4
            with:
                fetch-depth: 0

          - name: Get release version
            id: get-version
            uses: paulhatch/semantic-version@v5.4.0
            with:
                tag_prefix: "v"
                major_pattern: "(MAJOR)"
                minor_pattern: "(MINOR)"
                version_format: ${{ inputs.version_format || '${major}.${minor}.${patch}' }}
                search_commit_body: true

    tag_repo:
        runs-on: ubuntu-latest
        needs: [setup-version]
        if: inputs.tag_repo
        steps:
          - name: Create tag
            uses: actions/github-script@v7
            with:
                script: |
                    github.rest.git.createRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: 'refs/tags/${{ needs.setup-version.outputs.version_tag }}',
                    sha: context.sha
                    })
