name: Pull Request

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  pr-checks:
    name: Pre-commit checks and unit tests
    uses: KatKmiotek/reusable-workflows/.github/workflows/rust-pull-request.yml@v1.0.8

  setup-version:
    name: Set dev image version
    uses: ./.github/workflows/_set_version.yml
    with:
      version_format: "${major}.${minor}.${patch}-dev-pr${{ github.event.pull_request.number }}"


  deploy-dev:
    name: Deploy to dev
    uses: ./.github/workflows/_build_and_publish.yml
    needs: [pr-checks, setup-version]
    secrets: inherit
    with:
      environment: dev
      version: ${{ needs.setup-version.outputs.version }}
