name: Pull Request

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  pr-checks:
    name: Pull request checks
    uses: KatKmiotek/reusable-workflows/.github/workflows/rust-pull-request.yml@v1.0.0
