name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Package release
    uses: KatKmiotek/reusable-workflows/.github/workflows/rust-release.yml@v1.0.1
    with:
      binary_name: metric-collector
