name: Release

on:
  push:
    branches: [main]

jobs:
  setup-version:
    name: Tag project
    uses: ./.github/workflows/_set_version.yml
    with:
      tag_repo: true

  release:
    name: Package release
    needs: [setup-version]
    uses: KatKmiotek/reusable-workflows/.github/workflows/rust-release.yml@v1.0.8
    with:
      binary_name: metric-collector
      release_version: ${{ needs.setup-version.outputs.version_tag }}

  deploy:
    name: Deploy to ${{ matrix.environment }}
    needs: [setup-version, release]
    strategy:
      matrix:
        environment: [qa, staging]
    uses: ./.github/workflows/_build_and_publish.yml
    secrets: inherit
    with:
      environment: ${{ matrix.environment }}
      version: ${{ needs.setup-version.outputs.version }}-${{ matrix.environment }}

  deploy-production:
      needs: [deploy, setup-version, release]
      name: Deploy to Production
      uses: ./.github/workflows/_build_and_publish.yml
      secrets: inherit
      with:
        environment: production
        version: ${{ needs.setup-version.outputs.version }}-production
