name: Release

on:
  push:
    branches: [main]

jobs:
  setup-version:
    name: Tag project
    uses: ./.github/workflows/_set_version.yml
    with:
      tag_repo: true

  deploy-qa:
      name: Deploy to QA
      needs: [setup-version]
      uses: ./.github/workflows/_deploy.yml
      secrets: inherit
      with:
        environment: qa
        version: ${{ needs.setup-version.outputs.version }}-qa

  deploy-staging:
      name: Deploy to Staging
      needs: [setup-version]
      uses: ./.github/workflows/_deploy.yml
      secrets: inherit
      with:
        environment: staging
        version: ${{ needs.setup-version.outputs.version }}-staging

  deploy-production:
      needs: [deploy-staging, deploy-qa, setup-version]
      name: Deploy to Production
      uses: ./.github/workflows/_deploy.yml
      secrets: inherit
      with:
        environment: production
        version: ${{ needs.setup-version.outputs.version }}-production

  release:
    name: Package release
    needs: [setup-version]
    uses: KatKmiotek/reusable-workflows/.github/workflows/rust-release.yml@v1.0.2
    with:
      binary_name: metric-collector
      release_version: ${{ needs.setup-version.outputs.version }}
